# Generated by Django 6.0.3 on 2026-03-28 14:18

import django.db.models.deletion
import vendor_portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('qc_approved', 'QC Approved'), ('rejected', 'Rejected'), ('final_approved', 'Final Approved')], default='draft', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('material_grade', models.CharField(blank=True, max_length=100)),
                ('material_standard', models.CharField(blank=True, max_length=100)),
                ('tdc_number', models.CharField(blank=True, max_length=100)),
                ('maker', models.CharField(blank=True, max_length=255)),
                ('mill_certificate_number', models.CharField(blank=True, max_length=100)),
                ('raw_material_specification', models.CharField(blank=True, max_length=255)),
                ('manufacturing_process', models.CharField(blank=True, max_length=255)),
                ('heat_number', models.CharField(blank=True, max_length=100)),
                ('chemical_data', models.JSONField(blank=True, default=vendor_portal.models.default_chemical_data)),
                ('mechanical_data', models.JSONField(blank=True, default=vendor_portal.models.default_mechanical_data)),
                ('heat_treatment_details', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('qc_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('final_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('qc', 'QC'), ('purchase', 'Purchase'), ('admin', 'Admin')], max_length=20)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendor_portal.vendordocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('qc_approved', 'QC Approved'), ('purchase_approved', 'Purchase Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='vendor_portal.vendordocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['status'], name='vendor_port_status_2a514a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['vendor', 'status'], name='vendor_port_vendor__6012a7_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['document_number'], name='vendor_port_documen_24a578_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['role', 'decision'], name='vendor_port_role_addb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['document', 'role'], name='vendor_port_documen_c94638_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['document', 'created_at'], name='vendor_port_documen_d95001_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='vendor_port_action_d83811_idx'),
        ),
    ]
