# Generated by Django 6.0.3 on 2026-03-28 16:23

import vendor_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_portal', '0003_alter_auditlog_action_documentrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordocument',
            name='authorized_signatory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='barcode_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='certificate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='forging_data',
            field=models.JSONField(blank=True, default=vendor_portal.models.default_forging_data),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='line_items',
            field=models.JSONField(blank=True, default=vendor_portal.models.default_line_items),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='raw_material_standard',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='signatory_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendordocument',
            name='heat_treatment_details',
            field=models.JSONField(blank=True, default=vendor_portal.models.default_heat_treatment_details),
        ),
    ]
