# Generated by Django 6.0.3 on 2026-03-31 16:18

from django.db import migrations, models


def migrate_workflow_values(apps, schema_editor):
    VendorDocument = apps.get_model("vendor_portal", "VendorDocument")
    AuditLog = apps.get_model("vendor_portal", "AuditLog")

    VendorDocument.objects.filter(status="qc_approved").update(status="purchase_approved")
    AuditLog.objects.filter(action="qc_approved").update(action="purchase_approved")


def reverse_migrate_workflow_values(apps, schema_editor):
    VendorDocument = apps.get_model("vendor_portal", "VendorDocument")
    AuditLog = apps.get_model("vendor_portal", "AuditLog")

    VendorDocument.objects.filter(status="purchase_approved").update(status="qc_approved")
    AuditLog.objects.filter(action="purchase_approved").update(action="qc_approved")


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_portal', '0005_companydata_vendorprofile'),
    ]

    operations = [
        migrations.RunPython(migrate_workflow_values, reverse_migrate_workflow_values),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('purchase_approved', 'Purchase Approved'), ('qa_approved', 'QA Approved'), ('rejected', 'Rejected'), ('pdf_downloaded', 'PDF Downloaded')], max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('qc', 'QA'), ('purchase', 'Purchase'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('qc', 'QA'), ('purchase', 'Purchase'), ('admin', 'Admin')], default='vendor', help_text='Controls which stage of the VQMS workflow the user can access.', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendordocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('purchase_approved', 'Purchase Approved'), ('rejected', 'Rejected'), ('final_approved', 'Final Approved')], default='draft', max_length=20),
        ),
    ]
